# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5b8f5f6a373719367faf5d4fd2816940ca501da311da4cc5e5a9441793b9e242f8af069e93a5bbc19bed6543539b0e8e5617d06337072ee628f3da2688e7a5

test:
  secret_key_base: 8bff747ff96f4b6868616f795073e4a92adb57ebee87cf7b3a9de14a0b02a5895357ed789580e165f30fd593d47defcf34d397b710ba689d794c223e9914ac1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
